import json
import os
import subprocess

from mcp.server.mcpserver import MCPServer

# ============================================================
# AI Performance MCP Server
# ============================================================

mcp = MCPServer("AI Performance MCP")


# ============================================================
# Project paths
# ============================================================

BASE_DIR = os.path.dirname(
    os.path.dirname(
        os.path.abspath(__file__)
    )
)

METRICS_FILE = os.path.join(
    BASE_DIR,
    "python-engine",
    "metrics.json"
)


# ============================================================
# MCP Tool: Get Performance Metrics
# ============================================================

@mcp.tool()
def get_performance_metrics() -> dict:
    """
    Return the latest performance test metrics generated
    by the Python performance analyzer.
    """

    # Check whether metrics.json exists
    if not os.path.exists(METRICS_FILE):
        return {
            "status": "ERROR",
            "message": "Performance metrics file was not found.",
            "file": METRICS_FILE
        }

    try:

        # Read metrics generated by analyzer.py
        with open(
            METRICS_FILE,
            "r",
            encoding="utf-8"
        ) as file:

            metrics = json.load(file)

        # Return controlled performance evidence
        return {
            "status": "SUCCESS",
            "source": "python-engine/metrics.json",
            "metrics": metrics
        }

    except json.JSONDecodeError as error:

        return {
            "status": "ERROR",
            "message": "metrics.json contains invalid JSON.",
            "details": str(error)
        }

    except Exception as error:

        return {
            "status": "ERROR",
            "message": "Unable to read performance metrics.",
            "details": str(error)
        }
    # ============================================================
# MCP Tool: Get SLA Status
# ============================================================

@mcp.tool()
def get_sla_status() -> dict:
    """
    Return the SLA validation results from the latest performance test.
    """

    # Check whether metrics.json exists
    if not os.path.exists(METRICS_FILE):
        return {
            "status": "ERROR",
            "message": "Performance metrics file was not found.",
            "file": METRICS_FILE
        }

    try:

        # Read metrics generated by analyzer.py
        with open(
            METRICS_FILE,
            "r",
            encoding="utf-8"
        ) as file:

            metrics = json.load(file)

        # Extract SLA information
        sla = metrics.get("sla", {})

        # Return controlled SLA evidence
        return {
            "status": "SUCCESS",
            "source": "python-engine/metrics.json",
            "sla": sla
        }

    except json.JSONDecodeError as error:

        return {
            "status": "ERROR",
            "message": "metrics.json contains invalid JSON.",
            "details": str(error)
        }

    except Exception as error:

        return {
            "status": "ERROR",
            "message": "Unable to read SLA information.",
            "details": str(error)
        }
# ============================================================
# MCP Tool: Get RCA Evidence
# ============================================================

@mcp.tool()
def get_rca_evidence() -> dict:
    """
    Return consolidated performance, transaction, failure,
    and SLA evidence for AI-powered root cause analysis.
    """

    if not os.path.exists(METRICS_FILE):
        return {
            "status": "ERROR",
            "message": "Performance metrics file was not found.",
            "file": METRICS_FILE
        }

    try:

        with open(
            METRICS_FILE,
            "r",
            encoding="utf-8"
        ) as file:

            metrics = json.load(file)

        test_summary = metrics.get(
            "test_summary",
            {}
        )

        performance = metrics.get(
            "performance_metrics",
            {}
        )

        transaction_summary = metrics.get(
            "transaction_summary",
            {}
        )

        failure_analysis = metrics.get(
            "failure_analysis",
            {}
        )

        sla = metrics.get(
            "sla",
            {}
        )

        return {
            "status": "SUCCESS",
            "evidence": {
                "test_summary": test_summary,
                "performance_metrics": performance,
                "transaction_summary": transaction_summary,
                "failure_analysis": failure_analysis,
                "sla": sla
            }
        }

    except json.JSONDecodeError as error:

        return {
            "status": "ERROR",
            "message": "metrics.json contains invalid JSON.",
            "details": str(error)
        }

    except Exception as error:

        return {
            "status": "ERROR",
            "message": "Unable to read RCA evidence.",
            "details": str(error)
        }
# ============================================================
# MCP Tool: Get Kubernetes Metrics
# ============================================================

@mcp.tool()
def get_kubernetes_metrics() -> dict:
    """
    Return current Kubernetes node and pod CPU/memory metrics
    from the Kubernetes Metrics Server.
    """

    try:
        env = os.environ.copy()

        node_result = subprocess.run(
            ["kubectl", "top", "nodes"],
            capture_output=True,
            text=True,
            env=env
        )

        pod_result = subprocess.run(
            ["kubectl", "top", "pods"],
            capture_output=True,
            text=True,
            env=env
        )

        return {
            "status": "SUCCESS" if node_result.returncode == 0 and pod_result.returncode == 0 else "ERROR",
            "source": "Kubernetes Metrics Server",
            "environment": {
                "KUBECONFIG": env.get("KUBECONFIG"),
                "PATH": env.get("PATH")
            },
            "node_return_code": node_result.returncode,
            "node_stdout": node_result.stdout.strip(),
            "node_stderr": node_result.stderr.strip(),
            "pod_return_code": pod_result.returncode,
            "pod_stdout": pod_result.stdout.strip(),
            "pod_stderr": pod_result.stderr.strip()
        }

    except Exception as error:

        return {
            "status": "ERROR",
            "message": "Unexpected error retrieving Kubernetes metrics.",
            "details": str(error)
        }
# ============================================================
# Start MCP Server
# ============================================================

if __name__ == "__main__":

    mcp.run()