import json
import os

from mcp.server.mcpserver import MCPServer


# ============================================================
# AI Performance MCP Server
# ============================================================

mcp = MCPServer("AI Performance MCP")


# ============================================================
# Project paths
# ============================================================

BASE_DIR = os.path.dirname(
    os.path.dirname(
        os.path.abspath(__file__)
    )
)

METRICS_FILE = os.path.join(
    BASE_DIR,
    "python-engine",
    "metrics.json"
)


# ============================================================
# MCP Tool: Get Performance Metrics
# ============================================================

@mcp.tool()
def get_performance_metrics() -> dict:
    """
    Return the latest performance test metrics generated
    by the Python performance analyzer.
    """

    # Check whether metrics.json exists
    if not os.path.exists(METRICS_FILE):
        return {
            "status": "ERROR",
            "message": "Performance metrics file was not found.",
            "file": METRICS_FILE
        }

    try:

        # Read metrics generated by analyzer.py
        with open(
            METRICS_FILE,
            "r",
            encoding="utf-8"
        ) as file:

            metrics = json.load(file)

        # Return controlled performance evidence
        return {
            "status": "SUCCESS",
            "source": "python-engine/metrics.json",
            "metrics": metrics
        }

    except json.JSONDecodeError as error:

        return {
            "status": "ERROR",
            "message": "metrics.json contains invalid JSON.",
            "details": str(error)
        }

    except Exception as error:

        return {
            "status": "ERROR",
            "message": "Unable to read performance metrics.",
            "details": str(error)
        }
    # ============================================================
# MCP Tool: Get SLA Status
# ============================================================

@mcp.tool()
def get_sla_status() -> dict:
    """
    Return the SLA validation results from the latest performance test.
    """

    # Check whether metrics.json exists
    if not os.path.exists(METRICS_FILE):
        return {
            "status": "ERROR",
            "message": "Performance metrics file was not found.",
            "file": METRICS_FILE
        }

    try:

        # Read metrics generated by analyzer.py
        with open(
            METRICS_FILE,
            "r",
            encoding="utf-8"
        ) as file:

            metrics = json.load(file)

        # Extract SLA information
        sla = metrics.get("sla", {})

        # Return controlled SLA evidence
        return {
            "status": "SUCCESS",
            "source": "python-engine/metrics.json",
            "sla": sla
        }

    except json.JSONDecodeError as error:

        return {
            "status": "ERROR",
            "message": "metrics.json contains invalid JSON.",
            "details": str(error)
        }

    except Exception as error:

        return {
            "status": "ERROR",
            "message": "Unable to read SLA information.",
            "details": str(error)
        }
# ============================================================
# MCP Tool: Get RCA Evidence
# ============================================================

@mcp.tool()
def get_rca_evidence() -> dict:
    """
    Return consolidated performance and SLA evidence
    for AI-powered root cause analysis.
    """

    if not os.path.exists(METRICS_FILE):
        return {
            "status": "ERROR",
            "message": "Performance metrics file was not found.",
            "file": METRICS_FILE
        }

    try:

        with open(
            METRICS_FILE,
            "r",
            encoding="utf-8"
        ) as file:

            metrics = json.load(file)

        test_summary = metrics.get(
            "test_summary",
            {}
        )

        performance = metrics.get(
            "performance_metrics",
            {}
        )

        sla = metrics.get(
            "sla",
            {}
        )

        return {
            "status": "SUCCESS",
            "evidence": {
                "test_summary": test_summary,
                "performance_metrics": performance,
                "sla": sla
            }
        }

    except json.JSONDecodeError as error:

        return {
            "status": "ERROR",
            "message": "metrics.json contains invalid JSON.",
            "details": str(error)
        }

    except Exception as error:

        return {
            "status": "ERROR",
            "message": "Unable to read RCA evidence.",
            "details": str(error)
        }

# ============================================================
# Start MCP Server
# ============================================================

if __name__ == "__main__":

    mcp.run()