apiVersion: v1
kind: Service
metadata:
  name: ai-perf-order-service
spec:
  selector:
    app: ai-perf-order-service
  type: NodePort
  ports:
    - protocol: TCP
      port: 3002
      targetPort: 3002
      nodePort: 30002